---
- hosts: all
  connection: local
  become: true
  vars: 
    src_directory: /tmp
  tasks:
    - name: 'Download InfluxDB 2.0'
      get_url: 
        url: https://dl.influxdata.com/influxdb/releases/influxdb_2.0.0-beta.10_linux_amd64.tar.gz
        dest: "{{src_directory}}"
    - name: 'Extract InfluxDB'
      unarchive:
        src: "{{src_directory}}/influxdb_2.0.0-beta.10_linux_amd64.tar.gz"
        dest: "{{src_directory}}"
        creates: "{{src_directory}}/influxdb_2.0.0-beta.10_linux_amd64"
    - name: "Make sure InfluxDB User"
      user:
        name: influxdb
    - name: 'Copy files'
      copy: src={{item.src}} dest={{item.dest}} owner=influxdb mode=0775
      with_items:
        - { src: "{{src_directory}}/influxdb_2.0.0-beta.10_linux_amd64/influxd", dest: /usr/local/bin/}
        - { src: "{{src_directory}}/influxdb_2.0.0-beta.10_linux_amd64/influx", dest: /usr/local/bin/}
        - { src: "{{src_directory}}/influxdb2.service", dest: /lib/systemd/system}
    - name: "Make sure service is started"
      systemd:
        name: influxdb2
        state: started
        enabled: yes