# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 9999, host: 9999
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "ansible_local" do |ansible|
   ansible.become = true   
   ansible.playbook = "playbook.yaml"
  end
end
